const docsBase = '/docs';

const chapter = (config) => ({
  ...config,
  href: `${docsBase}/${config.docId}`,
});

export const learningRoadmaps = {
  'course-preparation': {
    id: 'course-preparation',
    part: 'Part 0',
    title: '课程准备学习路线',
    subtitle: '先搭环境，再建工作区，最后按需接入 AI 辅助工具',
    sourceTitle: 'AI 辅助嵌入式 Linux 多平台桌面系统 UI 移植实战',
    version: '课程资料未标注版本',
    platform: 'Windows 10/11 · Ubuntu 24.04',
    outcome: '得到可复现的 Ubuntu 开发环境和可控的 AI Agent 工作区。',
    goals: [
      '完成 Windows 虚拟化与 VMware 安装检查',
      '建立可登录、可快照的 Ubuntu 24.04 虚拟机',
      '准备课程工作区、通用工具和 Node.js 24',
      '按需选择 AI 辅助工具并完成首次安全体验',
    ],
    chapters: [
      chapter({
        id: 'vmware',
        number: '00',
        title: 'VMware 安装',
        shortTitle: 'VMware',
        docId: 'course-preparation/vmware-workstation',
        description: '确认硬件虚拟化并安装可信版本的 VMware Workstation。',
        outcome: 'VMware 主界面可打开，版本与安装来源已记录。',
        evidence: ['设备状态', '版本记录'],
      }),
      chapter({
        id: 'ubuntu-vm',
        number: '01',
        title: 'Ubuntu 24.04 虚拟机',
        shortTitle: 'Ubuntu VM',
        docId: 'course-preparation/ubuntu-24-vm',
        description: '导入课程虚拟机，检查资源并完成首次登录。',
        outcome: 'Ubuntu 24.04 可正常登录、关机并保留工作副本。',
        evidence: ['登录状态', '虚拟机配置'],
        prerequisites: ['vmware'],
      }),
      chapter({
        id: 'base-env',
        number: '02',
        title: '虚拟机基础配置',
        shortTitle: '基础环境',
        docId: 'course-preparation/vm-base-setup',
        description: '配置网络、VMware Tools、工作区和通用开发工具。',
        outcome: '环境体检日志已保存，并创建基础开发环境快照。',
        evidence: ['命令输出', '日志文件', '快照'],
        prerequisites: ['ubuntu-vm'],
      }),
      chapter({
        id: 'claude-code',
        number: '03',
        title: 'Claude Code',
        shortTitle: 'Claude Code',
        docId: 'course-preparation/claude-code',
        description: '完成安装登录，并用 Plan 模式执行第一次只读提问。',
        outcome: 'Claude Code 能在练习目录中完成只读分析。',
        evidence: ['版本输出', '只读结果'],
        prerequisites: ['base-env'],
        optional: true,
      }),
      chapter({
        id: 'codex-cli',
        number: '04',
        title: 'Codex CLI',
        shortTitle: 'Codex CLI',
        docId: 'course-preparation/codex-cli',
        description: '使用 ChatGPT 登录，以 Read Only 权限完成首次任务。',
        outcome: 'Codex CLI 能在限定工作目录内进行只读检查。',
        evidence: ['认证状态', '权限状态'],
        prerequisites: ['base-env'],
        optional: true,
      }),
      chapter({
        id: 'deepseek-harness',
        number: '05',
        title: 'DeepSeek Harness',
        shortTitle: 'Harness',
        docId: 'course-preparation/deepseek-harness',
        description: '启动 Web 控制台，核对端口、工作区和只读权限。',
        outcome: '浏览器可访问 3080 页面，工作区保持 Read Only。',
        evidence: ['端口响应', '页面状态', '权限状态'],
        prerequisites: ['base-env'],
        optional: true,
        warning: 'Provider 配置对应的后续章节尚未包含在源资料中。',
      }),
    ],
    context: {
      title: '课程环境分层与章节映射',
      principle: '先稳定宿主机和虚拟机，再安装工具；AI Agent 始终从最小权限开始。',
      rows: [
        {
          label: 'Windows 宿主机',
          detail: '虚拟化与本机资源',
          tone: 'host',
          items: [
            {label: '硬件虚拟化', chapterId: 'vmware'},
            {label: 'VMware Workstation', chapterId: 'vmware'},
          ],
        },
        {
          label: 'Ubuntu 虚拟机',
          detail: '统一 Linux 开发环境',
          tone: 'system',
          items: [
            {label: 'Ubuntu 24.04', chapterId: 'ubuntu-vm'},
            {label: 'VMware Tools', chapterId: 'base-env'},
            {label: '网络与 Xorg', chapterId: 'base-env'},
          ],
        },
        {
          label: '课程工作区',
          detail: '工具、日志与快照',
          tone: 'workspace',
          items: [
            {label: '通用开发工具', chapterId: 'base-env'},
            {label: 'Node.js 24', chapterId: 'base-env'},
            {label: '环境体检记录', chapterId: 'base-env'},
          ],
        },
        {
          label: 'AI 辅助工具',
          detail: '只读起步与权限边界',
          tone: 'tool',
          items: [
            {label: 'Claude Code', chapterId: 'claude-code'},
            {label: 'Codex CLI', chapterId: 'codex-cli'},
            {label: 'DeepSeek Harness', chapterId: 'deepseek-harness'},
          ],
        },
      ],
    },
  },

  'v853-tina-linux': {
    id: 'v853-tina-linux',
    part: 'Part 1',
    title: 'V853 系统开发学习路线',
    subtitle: '从 SDK 环境走到固件与 LCD/Touch 板级验证',
    sourceTitle: 'AI 辅助嵌入式 Linux 多平台桌面系统 UI 移植实战',
    version: '课程资料未标注版本',
    platform: 'V853-100ASK · Tina Linux 4.9.191',
    outcome: '得到可烧录的 V853 固件，并确认 LCD 与触摸硬件基线可用。',
    goals: [
      '认识 Tina SDK 目录与环境脚本',
      '完成 V853 SDK 配置、编译和打包',
      '建立固件、连接与烧录检查边界',
      '验证 LCD 与 Touch 的设备节点和示例程序',
    ],
    chapters: [
      chapter({
        id: 'ubuntu-sdk-env',
        number: '04',
        title: 'Ubuntu 环境搭建',
        shortTitle: 'SDK 环境',
        docId: 'v853-tina-linux/ubuntu-environment',
        description: '把 Tina SDK 搬到 Ubuntu 24.04，并安装编译依赖。',
        outcome: 'SDK 完整解压，依赖安装完成且路径可访问。',
        evidence: ['目录状态', '依赖输出'],
      }),
      chapter({
        id: 'tina-sdk',
        number: '05',
        title: 'Tina SDK 介绍',
        shortTitle: '认识 SDK',
        docId: 'v853-tina-linux/tina-sdk-overview',
        description: '加载环境脚本，认识构建相关的常用目录。',
        outcome: '能定位环境脚本、配置、源码、输出与打包目录。',
        evidence: ['目录检查', '环境状态'],
        prerequisites: ['ubuntu-sdk-env'],
      }),
      chapter({
        id: 'sdk-build',
        number: '06–07',
        title: 'SDK 配置与编译',
        shortTitle: '编译与打包',
        docId: 'v853-tina-linux/v853-sdk-build',
        description: '选择 100ASK 配置，完成传统或 Agent 辅助编译与打包。',
        outcome: '完整固件存在且大小非 0，编译与打包退出码已记录。',
        evidence: ['退出码', '固件文件', '构建日志'],
        prerequisites: ['tina-sdk'],
      }),
      chapter({
        id: 'firmware-flashing',
        number: '08',
        title: '固件烧录',
        shortTitle: '驱动与烧录',
        docId: 'v853-tina-linux/firmware-flashing',
        description: '安装 Windows USB 驱动并配置 LYNX 芯桥。',
        outcome: 'USB 设备被正确识别，单板连接信息已保存。',
        evidence: ['USB 设备状态', '连接配置'],
        prerequisites: ['sdk-build'],
        incomplete: true,
        warning: '源资料中的 AI Agent 烧录与完整验收步骤仍待补充。',
      }),
      chapter({
        id: 'peripheral-validation',
        number: '10',
        title: '外设验证',
        shortTitle: 'LCD / Touch',
        docId: 'v853-tina-linux/peripheral-validation',
        description: '运行系统示例，分别观察 LCD 画面和 Touch 反馈。',
        outcome: '记录 /dev/fb0、Touch 节点与 lv_examples 的实测结果。',
        evidence: ['串口日志', '设备节点', '人工观察'],
        prerequisites: ['firmware-flashing'],
      }),
    ],
    context: {
      title: 'V853 固件生成与板级验证链路',
      principle: '先证明 SDK 构建链可复现，再烧录；最后用系统示例建立 LCD/Touch 硬件基线。',
      rows: [
        {
          label: 'Ubuntu 主机',
          detail: 'SDK 存放与依赖环境',
          tone: 'host',
          items: [
            {label: 'Ubuntu 24.04', chapterId: 'ubuntu-sdk-env'},
            {label: '编译依赖', chapterId: 'ubuntu-sdk-env'},
          ],
        },
        {
          label: 'Tina SDK',
          detail: '配置、编译与打包',
          tone: 'system',
          items: [
            {label: 'envsetup / lunch', chapterId: 'tina-sdk'},
            {label: 'make', chapterId: 'sdk-build'},
            {label: 'pack', chapterId: 'sdk-build'},
          ],
        },
        {
          label: '固件与连接',
          detail: 'Windows 驱动和 LYNX',
          tone: 'workspace',
          items: [
            {label: '完整 .img 固件', chapterId: 'sdk-build'},
            {label: 'FEL / USB 驱动', chapterId: 'firmware-flashing'},
            {label: 'LYNX 单板配置', chapterId: 'firmware-flashing'},
          ],
        },
        {
          label: 'V853 开发板',
          detail: 'LCD 与触摸硬件',
          tone: 'hardware',
          items: [
            {label: '/dev/fb0', chapterId: 'peripheral-validation'},
            {label: 'ft6336', chapterId: 'peripheral-validation'},
            {label: 'lv_examples', chapterId: 'peripheral-validation'},
          ],
        },
      ],
    },
  },

  'lvgl9-porting': {
    id: 'lvgl9-porting',
    part: 'Part 2',
    title: 'LVGL 9 移植学习路线',
    subtitle: '从固定源码到显示、触摸、资源、性能和 Tina SDK 集成',
    sourceTitle: 'AI 辅助嵌入式 Linux 多平台桌面系统 UI 移植实战',
    version: 'LVGL 9.4',
    platform: 'V853-100ASK · fbdev · evdev',
    outcome: '得到能显示、能触摸、可持续刷新并可集成进 Tina SDK 的 LVGL 9 应用。',
    goals: [
      '固定课程使用的 LVGL 9 源码版本',
      '完成 V853 工程搭建与交叉编译',
      '打通 fbdev 显示和 evdev 触摸输入',
      '加入界面资源并完成性能与集成检查',
    ],
    chapters: [
      chapter({
        id: 'pin-source',
        number: '13',
        title: '固定 LVGL 9 源码',
        shortTitle: '固定源码',
        docId: 'lvgl9-porting/pin-lvgl9-source',
        description: '获取 LVGL 9 源码并固定到课程验证版本。',
        outcome: '远端、分支与当前提交检查结果可复现。',
        evidence: ['Git 状态', '提交记录'],
      }),
      chapter({
        id: 'build-project',
        number: '16',
        title: 'AI 搭建 V853 工程',
        shortTitle: '工程搭建',
        docId: 'lvgl9-porting/ai-build-lvgl9-project',
        description: '明确部署、触摸和构建方式后，让 AI 创建独立工程。',
        outcome: 'V853 LVGL 9 工程完成交叉编译并生成目标程序。',
        evidence: ['构建日志', '目标文件'],
        prerequisites: ['pin-source'],
      }),
      chapter({
        id: 'lcd-display',
        number: '17',
        title: '让界面显示到 LCD',
        shortTitle: 'fbdev 显示',
        docId: 'lvgl9-porting/lvgl9-on-lcd',
        description: '基于实测 /dev/fb0 参数创建并绑定 LVGL 显示对象。',
        outcome: 'LCD 出现预期 LVGL 画面，而不只是程序编译成功。',
        evidence: ['运行日志', 'LCD 观察'],
        prerequisites: ['build-project'],
      }),
      chapter({
        id: 'touch-input',
        number: '18',
        title: '让触摸控制界面',
        shortTitle: 'evdev 触摸',
        docId: 'lvgl9-porting/touch-input',
        description: '创建 evdev 输入对象并绑定到正确的显示对象。',
        outcome: '点击、拖动、松开与四角坐标方向均能验证。',
        evidence: ['设备节点', '触摸观察'],
        prerequisites: ['lcd-display'],
        warning: '设备节点与坐标参数必须使用第 10 节的板上实测值。',
      }),
      chapter({
        id: 'refresh-loop',
        number: '19',
        title: '持续刷新与响应',
        shortTitle: '刷新循环',
        docId: 'lvgl9-porting/refresh-loop',
        description: '建立 tick 与 timer handler 的持续运行关系。',
        outcome: '动画持续刷新，触摸操作能够及时响应。',
        evidence: ['运行状态', '交互观察'],
        prerequisites: ['touch-input'],
      }),
      chapter({
        id: 'ui-assets',
        number: '20',
        title: '中文字体和图片',
        shortTitle: '界面资源',
        docId: 'lvgl9-porting/fonts-and-images',
        description: '将字体和图片转换为适合 LVGL 工程使用的资源。',
        outcome: '中文文本和目标图片在开发板界面中正确显示。',
        evidence: ['资源文件', '界面观察'],
        prerequisites: ['refresh-loop'],
      }),
      chapter({
        id: 'performance',
        number: '21',
        title: '性能和稳定性',
        shortTitle: '性能检查',
        docId: 'lvgl9-porting/performance-and-stability',
        description: '建立 CPU、内存、帧率与长时间运行基线。',
        outcome: '关键性能数据有记录，持续运行没有阻断异常。',
        evidence: ['性能记录', '稳定性日志'],
        prerequisites: ['ui-assets'],
      }),
      chapter({
        id: 'tina-integration',
        number: '22',
        title: '集成到 Tina SDK',
        shortTitle: 'SDK 集成',
        docId: 'lvgl9-porting/integrate-with-tina-sdk',
        description: '把独立工程纳入 Tina SDK 的包与固件构建流程。',
        outcome: 'LVGL 9 应用可随 Tina SDK 构建并进入目标系统。',
        evidence: ['包配置', '固件产物', '板上运行'],
        prerequisites: ['performance'],
      }),
    ],
    context: {
      title: 'LVGL 应用到硬件的分层映射',
      principle: '先应用与运行时，再 Linux 驱动，最后硬件；排错时沿同一链路逐层验证。',
      rows: [
        {
          label: '界面应用',
          detail: '控件、字体与图片',
          tone: 'host',
          items: [
            {label: '工程结构', chapterId: 'build-project'},
            {label: '中文字体', chapterId: 'ui-assets'},
            {label: '图片资源', chapterId: 'ui-assets'},
          ],
        },
        {
          label: 'LVGL 运行时',
          detail: '显示、输入与刷新',
          tone: 'system',
          items: [
            {label: '显示对象', chapterId: 'lcd-display'},
            {label: '输入对象', chapterId: 'touch-input'},
            {label: 'tick / timer', chapterId: 'refresh-loop'},
          ],
        },
        {
          label: 'Linux 驱动接口',
          detail: '用户态设备访问',
          tone: 'workspace',
          items: [
            {label: 'fbdev', chapterId: 'lcd-display'},
            {label: 'evdev', chapterId: 'touch-input'},
            {label: '性能观测', chapterId: 'performance'},
          ],
        },
        {
          label: 'V853 硬件',
          detail: '显示与输入设备',
          tone: 'hardware',
          items: [
            {label: 'LCD', chapterId: 'lcd-display'},
            {label: 'Touch', chapterId: 'touch-input'},
            {label: 'Tina 固件', chapterId: 'tina-integration'},
          ],
        },
      ],
    },
  },
  'edgeos-v853-porting': {
    id: 'edgeos-v853-porting',
    part: 'Part 3',
    title: 'EdgeOS V853 移植学习路线',
    subtitle: '从核心桌面 UI 开始，把产品形态接到已经验证的 V853 LVGL 运行时',
    sourceTitle: 'EdgeOS Desktop V853 Port',
    version: 'EdgeOS SDK v1.0.2 snapshot · LVGL 9.4',
    platform: 'V853-100ASK · Tina Linux · fbdev · evdev',
    outcome: '得到可构建、可启动、可触摸导航，并能用证据验收的 EdgeOS Desktop 核心 UI。',
    goals: [
      '审计 EdgeOS 源码、LVGL 版本、Tina 软件包与历史验证证据',
      '把桌面入口与内容页面改造成分辨率无关的横竖屏布局',
      '复用 fbdev、evdev 与刷新循环，区分点击、滑动和绘图输入',
      '通过构建日志、启动标志和真机操作清单完成分层验收',
    ],
    chapters: [
      chapter({
        id: 'desktop-ui',
        number: '26',
        title: 'EdgeOS 桌面 UI 与导航',
        shortTitle: '桌面 UI',
        docId: 'edgeos-v853-porting/edgeos-desktop-ui',
        description: '分析当前 V853 端口，适配核心桌面、八个应用入口、页面切换与触摸交互。',
        outcome: '桌面在横屏与竖屏上完整显示，入口可点击、页面可返回、绘图输入连续。',
        evidence: ['源码审计', '构建日志', '启动标志', '真机照片'],
        warning: '当前横向目标屏幕已有显示证据；触摸导航和竖向目标屏幕仍须分别完成真机验收。',
      }),
      chapter({
        id: 'settings',
        number: '27',
        title: 'Settings 设置中心适配',
        shortTitle: 'Settings',
        docId: 'edgeos-v853-porting/edgeos-settings',
        description: '适配只读系统信息、长文本布局、滚动区域和返回路径，并以板端真实数据替换静态占位值。',
        outcome: '设置中心可在不同屏幕形态下完整显示和导航；真实信息、失败状态与未接通功能边界清晰。',
        evidence: ['源码审计', '构建日志', '页面日志', '真机截图'],
        warning: '网络、语言、时间、显示等设置必须区分 UI 已适配与系统服务已接通。',
        prerequisites: ['desktop-ui'],
      }),
      chapter({
        id: 'settings-services',
        number: '28',
        title: '设置中心常用功能',
        shortTitle: '系统设置',
        docId: 'edgeos-v853-porting/edgeos-settings-services',
        description: '接入 Wi-Fi 扫描与配网、背光、声音、桌面时间偏好、启动应用和电源操作。',
        outcome: '分类设置页面连接真实 Linux 后端，具备配置保存、错误反馈和危险操作确认。',
        evidence: ['SDK 接口审计', '后台逻辑测试', '驱动回读', '实机截图'],
        warning: '真实热点认证、实际音频输出和关机上电需单独验收，不能由 UI 或模拟测试推断通过。',
        prerequisites: ['settings'],
      }),
    ],
    context: {
      title: 'EdgeOS Desktop 到 V853 硬件的移植边界',
      principle: '先保证核心 UI 可构建、可导航、可验收，再逐项接入 Camera、NPU 与 OTA 服务。',
      rows: [
        {
          label: '核心桌面',
          detail: '主页、入口与内容页',
          tone: 'host',
          items: [
            {label: '八个入口', chapterId: 'desktop-ui'},
            {label: 'Settings', chapterId: 'settings'},
            {label: 'Drawing', chapterId: 'desktop-ui'},
          ],
        },
        {
          label: 'LVGL 运行时',
          detail: '显示、触摸与定时器',
          tone: 'system',
          items: [
            {label: '自适应显示', chapterId: 'desktop-ui'},
            {label: 'Touch / evdev', chapterId: 'desktop-ui'},
            {label: 'tick / timer', chapterId: 'desktop-ui'},
          ],
        },
        {
          label: 'Tina 交付',
          detail: '软件包、服务与追溯',
          tone: 'workspace',
          items: [
            {label: 'v853-edgeos-desktop', chapterId: 'desktop-ui'},
            {label: 'S99edgeos-v853', chapterId: 'desktop-ui'},
            {label: 'Build ID', chapterId: 'desktop-ui'},
          ],
        },
        {
          label: '后续能力',
          detail: '当前不宣称已经移植',
          tone: 'hardware',
          items: [
            {label: 'Camera / MPP', chapterId: 'desktop-ui'},
            {label: 'NPU 应用', chapterId: 'desktop-ui'},
            {label: 'A/B OTA', chapterId: 'desktop-ui'},
          ],
        },
      ],
    },
  },
};

export function getLearningRoadmap(courseId) {
  return learningRoadmaps[courseId];
}
